name: test_web_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_echarts: any
  js: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true